language: rust

install:
  - wget https://github.com/jordansissel/xdotool/releases/download/v3.20150503.1/xdotool-3.20150503.1.tar.gz
  - tar xf xdotool-3.20150503.1.tar.gz
  - cd xdotool-3.20150503.1
  - make
  - sudo make install
